url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
title: "Ben Harvey UX Researcher & Engineer" # the name of your site, e.g. ACME Corp.
collections:
  case_studies:
    output: true
    permalink: /case-studies/:path
relative_links:
  enabled: true
  collections: true
plugins:
  - jekyll-relative-links